import React from "react";
import { useParams, Navigate } from "react-router-dom";

const LEGAL = {
  privacy: {
    title: "Privacy Policy",
    sections: [
      { h: "Information we collect", p: "LEAFVA collects only the minimum information needed to provide our services. Through our AI assistant, this typically includes your name, email, phone (optional), service category, urgency, and a description of your issue." },
      { h: "How we use it", p: "We use your data exclusively to respond to your inquiry, open and manage your service ticket, communicate progress, and improve the quality of our work." },
      { h: "Data retention", p: "Tickets and related communications are retained for up to 36 months for service quality and tax compliance purposes, then anonymized or deleted." },
      { h: "Your rights", p: "Under PIPEDA (Canada) and GDPR (EU), you may request access, correction, or deletion of your data. Email hello@leafva.com." },
      { h: "Sharing", p: "We do not sell your data. We share only with the subprocessors strictly required to deliver our services (e.g., email delivery, AI inference)." },
    ],
  },
  terms: {
    title: "Terms of Use",
    sections: [
      { h: "Acceptance", p: "By using leafva.com or our AI assistant, you agree to these terms and our Privacy Policy." },
      { h: "Service description", p: "LEAFVA provides IT consulting, networking, application development, system administration, AI services, and related subcontracted technical work in Ontario, Canada." },
      { h: "AI assistant", p: "The AI assistant is an intake tool. It is not a substitute for professional advice. Service contracts are entered into separately in writing." },
      { h: "Limitation of liability", p: "To the extent permitted by law, LEAFVA's liability is limited to fees paid by you for the specific service giving rise to the claim." },
      { h: "Governing law", p: "These terms are governed by the laws of the Province of Ontario, Canada." },
    ],
  },
  "ai-disclaimer": {
    title: "AI Disclaimer",
    sections: [
      { h: "AI-generated content", p: "Some communication with LEAFVA — including the chat assistant and automated email follow-ups — is generated by AI (Claude Sonnet 4.5). Outputs may occasionally contain inaccuracies." },
      { h: "Not professional advice", p: "AI-generated responses are informational. Final solutions and recommendations are reviewed by LEAFVA staff before contracts are signed." },
      { h: "Data handling", p: "AI inference is performed via secure third-party providers with strict data processing agreements. We never share sensitive personal data with the AI." },
      { h: "Human handoff", p: "You can always reach a human by typing 'speak to a person' in the chat or emailing hello@leafva.com." },
    ],
  },
  cookies: {
    title: "Cookie Policy",
    sections: [
      { h: "What we use", p: "LEAFVA uses only strictly necessary cookies and local storage to keep your AI chat session active and your admin login persistent. No advertising or tracking cookies are set." },
      { h: "Your choices", p: "You can disable cookies in your browser settings. Some functionality (admin dashboard, persistent chat) requires them." },
    ],
  },
};

export default function Legal() {
  const { doc } = useParams();
  const data = LEGAL[doc];
  if (!data) return <Navigate to="/legal/privacy" replace />;

  return (
    <div className="max-w-3xl mx-auto px-6 lg:px-8 py-24" data-testid={`page-legal-${doc}`}>
      <div className="text-xs uppercase tracking-[0.25em] text-gold mb-4">/ legal</div>
      <h1 className="font-display text-4xl sm:text-5xl text-white leading-tight mb-10">{data.title}</h1>
      <div className="space-y-10">
        {data.sections.map((s) => (
          <section key={s.h}>
            <h2 className="font-display text-xl text-gold mb-3">{s.h}</h2>
            <p className="text-white/70 leading-relaxed">{s.p}</p>
          </section>
        ))}
      </div>
      <p className="mt-16 text-xs text-muted-leaf">Last updated: {new Date().toLocaleDateString()}</p>
    </div>
  );
}
