import React, { useEffect, useState } from "react";
import { Wand2, Send } from "lucide-react";
import { toast } from "sonner";
import api from "../../lib/api";

export default function EmailComposer() {
  const [to, setTo] = useState("");
  const [recipientName, setRecipientName] = useState("");
  const [purpose, setPurpose] = useState("ticket_followup");
  const [tone, setTone] = useState("professional");
  const [context, setContext] = useState("");
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [composing, setComposing] = useState(false);
  const [sending, setSending] = useState(false);
  const [logs, setLogs] = useState([]);

  const loadLogs = () => api.get("/email/logs").then(r => setLogs(r.data));
  useEffect(() => { loadLogs(); }, []);

  const compose = async () => {
    if (!context.trim()) return toast.error("Provide context for the email");
    setComposing(true);
    try {
      const r = await api.post("/email/compose", { context, tone, purpose, recipient_name: recipientName });
      setSubject(r.data.subject);
      setBody(r.data.body);
      toast.success("Draft generated by AI");
    } catch (e) { toast.error("AI compose failed"); }
    finally { setComposing(false); }
  };

  const send = async () => {
    if (!to || !subject || !body) return toast.error("Recipient, subject and body required");
    setSending(true);
    try {
      const r = await api.post("/email/send", { to, subject, body });
      if (r.data.status === "sent") toast.success("Email sent");
      else if (r.data.status === "mocked") toast.info("Logged as draft (configure Resend in Settings to send)");
      else toast.error(r.data.error || "Failed");
      loadLogs();
    } catch (e) { toast.error("Send failed"); }
    finally { setSending(false); }
  };

  return (
    <div data-testid="admin-email-composer">
      <div className="mb-8">
        <div className="text-xs uppercase tracking-widest text-gold">/ ai email composer</div>
        <h1 className="font-display text-3xl text-white mt-2">AI Email Composer</h1>
      </div>

      <div className="grid lg:grid-cols-2 gap-6">
        <div className="space-y-4">
          <div className="rounded-2xl border border-subtle bg-leafva-card p-6 space-y-4">
            <div className="grid grid-cols-2 gap-3">
              <Inp label="To" v={to} on={setTo} testId="email-to" />
              <Inp label="Recipient name" v={recipientName} on={setRecipientName} testId="email-recipient-name" />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <Sel label="Purpose" v={purpose} on={setPurpose} opts={["ticket_followup", "invoice_reminder", "project_update", "welcome", "thank_you"]} testId="email-purpose" />
              <Sel label="Tone" v={tone} on={setTone} opts={["professional", "friendly", "urgent", "empathetic"]} testId="email-tone" />
            </div>
            <div>
              <label className="text-xs uppercase tracking-widest text-muted-leaf">Context / instructions</label>
              <textarea
                data-testid="email-context"
                rows={5}
                value={context}
                onChange={(e) => setContext(e.target.value)}
                placeholder="e.g. Customer's server crashed yesterday, we replaced the PSU and want to confirm everything is back up..."
                className="mt-2 w-full bg-black border border-subtle rounded-lg px-4 py-2.5 text-sm text-white"
              />
            </div>
            <button onClick={compose} disabled={composing} data-testid="email-compose-button" className="btn-gold w-full justify-center disabled:opacity-50">
              <Wand2 size={14} /> {composing ? "Drafting with AI…" : "AI Draft Email"}
            </button>
          </div>

          {(subject || body) && (
            <div className="rounded-2xl border border-subtle bg-leafva-card p-6 space-y-3">
              <Inp label="Subject" v={subject} on={setSubject} testId="email-subject" />
              <div>
                <label className="text-xs uppercase tracking-widest text-muted-leaf">Body</label>
                <textarea data-testid="email-body" rows={10} value={body} onChange={(e) => setBody(e.target.value)} className="mt-2 w-full bg-black border border-subtle rounded-lg px-4 py-2.5 text-sm text-white" />
              </div>
              <button onClick={send} disabled={sending} data-testid="email-send-button" className="btn-primary w-full justify-center disabled:opacity-50">
                <Send size={14} /> {sending ? "Sending…" : "Send via Resend"}
              </button>
            </div>
          )}
        </div>

        <div className="rounded-2xl border border-subtle bg-leafva-card overflow-hidden">
          <div className="px-6 py-4 border-b border-subtle text-xs uppercase tracking-widest text-gold">Recent emails</div>
          <div className="divide-y divide-white/5 max-h-[700px] overflow-y-auto">
            {logs.map(log => (
              <div key={log.id} className="px-6 py-4 text-sm" data-testid={`email-log-${log.id}`}>
                <div className="flex items-center justify-between">
                  <div className="text-white truncate">{log.subject}</div>
                  <span className={`text-[10px] uppercase tracking-wider px-2 py-0.5 rounded border ${
                    log.status === "sent" ? "bg-emerald-950 text-emerald-300 border-emerald-900" :
                    log.status === "failed" ? "bg-red-950 text-red-300 border-red-900" :
                    log.status === "mocked" ? "bg-yellow-950 text-yellow-300 border-yellow-900" :
                    "bg-zinc-900 text-zinc-400 border-zinc-800"
                  }`}>{log.status}</span>
                </div>
                <div className="text-xs text-muted-leaf mt-1">{log.to} · {new Date(log.created_at).toLocaleString()}</div>
                {log.error && <div className="text-xs text-red-400 mt-1">{log.error}</div>}
              </div>
            ))}
            {logs.length === 0 && <div className="px-6 py-12 text-center text-muted-leaf text-sm">No emails yet.</div>}
          </div>
        </div>
      </div>
    </div>
  );
}

function Inp({ label, v, on, testId }) {
  return (
    <div>
      <label className="text-xs uppercase tracking-widest text-muted-leaf">{label}</label>
      <input data-testid={testId} value={v} onChange={(e) => on(e.target.value)} className="mt-2 w-full bg-black border border-subtle rounded-lg px-4 py-2.5 text-sm text-white" />
    </div>
  );
}

function Sel({ label, v, on, opts, testId }) {
  return (
    <div>
      <label className="text-xs uppercase tracking-widest text-muted-leaf">{label}</label>
      <select data-testid={testId} value={v} onChange={(e) => on(e.target.value)} className="mt-2 w-full bg-black border border-subtle rounded-lg px-4 py-2.5 text-sm text-white">
        {opts.map(o => <option key={o} value={o}>{o.replace(/_/g, " ")}</option>)}
      </select>
    </div>
  );
}
